2022-03-16 02:27:48,522 INFO    MainThread:780 [wandb_setup.py:_flush():69] setting env: {}
2022-03-16 02:27:48,523 INFO    MainThread:780 [wandb_setup.py:_flush():69] setting login settings: {}
2022-03-16 02:27:48,523 INFO    MainThread:780 [wandb_init.py:_log_setup():336] Logging user logs to /workspace/graph-neural-pde/src/wandb/run-20220316_022748-339cql5f/logs/debug.log
2022-03-16 02:27:48,523 INFO    MainThread:780 [wandb_init.py:_log_setup():337] Logging internal logs to /workspace/graph-neural-pde/src/wandb/run-20220316_022748-339cql5f/logs/debug-internal.log
2022-03-16 02:27:48,523 INFO    MainThread:780 [wandb_init.py:init():369] calling init triggers
2022-03-16 02:27:48,523 INFO    MainThread:780 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2022-03-16 02:27:48,523 INFO    MainThread:780 [wandb_init.py:init():418] starting backend
2022-03-16 02:27:48,523 INFO    MainThread:780 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-16 02:27:48,537 INFO    MainThread:780 [backend.py:ensure_launched():123] starting backend process...
2022-03-16 02:27:48,556 INFO    MainThread:780 [backend.py:ensure_launched():128] started backend process with pid: 806
2022-03-16 02:27:48,559 INFO    MainThread:780 [wandb_init.py:init():423] backend started and connected
2022-03-16 02:27:48,561 INFO    MainThread:780 [wandb_init.py:init():465] updated telemetry
2022-03-16 02:27:48,562 INFO    MainThread:780 [wandb_init.py:init():484] communicating current version
2022-03-16 02:27:49,655 INFO    MainThread:780 [wandb_init.py:init():489] got version response 
2022-03-16 02:27:49,655 INFO    MainThread:780 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-16 02:28:19,656 INFO    MainThread:780 [interface.py:_communicate_run():642] couldn't get run from backend
2022-03-16 02:28:19,657 ERROR   MainThread:780 [wandb_init.py:init():501] backend process timed out
2022-03-16 02:28:19,657 ERROR   MainThread:780 [wandb_init.py:init():510] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-03-16 04:23:18,386 WARNING MainThread:780 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 513, in init
    backend.cleanup()
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/backend/backend.py", line 155, in cleanup
    self.wandb_process.join()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
